# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-30 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0004_auto_20180630_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='landmark',
            name='longitude',
        ),
    ]
