# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmarks', '0005_auto_20180630_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='latitude',
            field=models.FloatField(default='30.044281'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='longitude',
            field=models.FloatField(default='31.340002'),
        ),
    ]
